### ISSUE TITLE
Classes returning new instance

### ISSUE THREAD

**Issue by alexpovel** [danzat/3dpp#1]
Hi,

I came by this repo on the LaTeX subreddit. I have fumbled a lot with 3D tikz in the past as well, with some success here and there, but mostly headaches.

Combining LaTeX and Python is great. I know my way around the former, but am not super knowledgeable in Python, so bear that in mind.

One of the things I noticed was that class methods return a new instance of their own class, e.g.

```python
class Vector3:
    def __init__(self, x, y, z):
        self.x = x
        self.y = y
        self.z = z

    def scale(a, s):
        return Vector3(a.x * s, a.y * s, a.z * s)
```

These methods should probably return the class it**self** (hint, hint), not a wholly new instance, which quickly gets out of hand.

See for example:

```python
class Vector3:
    def __init__(self, x, y, z):
        self.x = x
        self.y = y
        self.z = z

    def scale(a, s):
        return Vector3(a.x * s, a.y * s, a.z * s)

    def scale_self(self, s):
        self.x *= s
        self.y *= s
        self.z *= s
        return self
```

The behaviour is now:

```bash
 ~/3dpp/master/python$
Python 3.8.1 (default, Jan 22 2020, 06:38:00) 
[GCC 9.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from lib.geometry import Vector3
>>> x = Vector3(1, 2, 3)
>>> x
(1, 2, 3)
>>> y = x.scale(2)
>>> y
(2, 4, 6)
>>> x is y
False
>>> z = x.scale_self(2)
>>> z
(2, 4, 6)
>>> z is x
True
>>> zz = x.scale_self(2).scale_self(2)
>>> zz
(8, 16, 24)
```

So the methods can now be chained, but more importantly, no new object is retained. A vector should stay the same vector (object). This can be checked with `id()` or as above, `is`.

I haven't even tried your software yet, I hope to do so soon and maybe get to do a full pull request.

**Comment by danzat** [comment]
Hi,

First of all, thanks so much for taking an interest.

As for your issue, I'm refraining from mutating the vector objects because I want to reuse them.
This is especially useful when declaring operators between vectors. Take for example this:
```
>>> u = Vector3(1, 1, 1)
>>> v = Vector3(1, 0, 2)
>>> w = Vector3(2, 1, 1)
>>> q = (u - v) ^ (u + w) # '^' is the cross product operator
```

Since I'm using `u` twice, mutating it would just make the expression impossible. Moreover, I would lose the value of `u` for later computations.
Granted, I could make copies of it, but it would just obscure the logic.

The sacrifice in performance/memory is so negligible, that the gain in conciseness and cleaner code is much more significant.

In theory I could have written it in C and use static allocations for everything, but I'm not writing a game, it's just a tools that supposed to be useful and extensible :)

**Comment by alexpovel** [comment]
Okay, cool! Thanks for the insight.

Of course, the impact is absolutely not noticeable here, I was more worried about style.
